### PR TITLE
Fvta draft

### PR DESCRIPTION
**Pull request by Hillowwold**

### CODE REVIEW

**Comment by Hillowwold** [comment]
Sorry guys, there is something wrong with github manager in VS2022, and I cann't push and merge the code in my VS2022. I am still trying to fix it. So as not to disrupt everyone's progress, I'm posting my update on FVTA here. The mian difference is all in fvta_step(). Don't forget to add uniform vec3 light_direction, which is currently glm::vec3(0.2f,0.2f,0.2f). Sorry for that once again.

**Comment by theolundqvist** [comment]
Ok! I Will take a look at it tomorrow

**Comment by theolundqvist** [comment]
You have to update the voxel.frag thats in shaders/edan35/voxel.frag. I will fix it this time. You have not uploaded your code for the uniforms, I will try to add them

**Comment by theolundqvist** [comment]
closing in favor of #14

**Pull request closed without merging**
